trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_WEBAPP_NAME: 'pankaj-react-todo'

steps:

# =========================
# Checkout Code
# =========================
- checkout: self
  displayName: 'Checkout Code'


# =========================
# Install Node.js
# =========================
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'


# =========================
# Install Dependencies
# =========================
- task: CmdLine@2
  displayName: 'npm install and build'
  inputs:
    script: |
      npm ci
      npm run build
    workingDirectory: '$(Build.SourcesDirectory)/ReactTodoUIMonolith'


# =========================
# Publish React Build
# =========================
- task: PublishBuildArtifacts@1
  displayName: 'Publish React Build'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/ReactTodoUIMonolith/build'
    ArtifactName: 'react-build'
    publishLocation: 'Container'


# =========================
# Deploy to Azure App Service
# =========================
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'YOUR-AZURE-SERVICE-CONNECTION'
    appType: 'webAppLinux'
    appName: '$(AZURE_WEBAPP_NAME)'
    package: '$(Build.SourcesDirectory)/ReactTodoUIMonolith/build'